name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ghc-version: ['9.4', '9.6', '9.8']
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Haskell
      uses: haskell-actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc-version }}
        cabal-version: 'latest'
        
    - name: Cache cabal packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: ${{ runner.os }}-cabal-${{ matrix.ghc-version }}-${{ hashFiles('**/*.cabal', 'cabal.project*') }}
        restore-keys: |
          ${{ runner.os }}-cabal-${{ matrix.ghc-version }}-
          ${{ runner.os }}-cabal-
          
    - name: Update cabal package index
      run: cabal update
      
    - name: Build dependencies
      run: cabal build --only-dependencies
      
    - name: Build project
      run: cabal build
      
    - name: Check executable runs
      run: cabal run notion-to-memgraph -- --help